language: android

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

jdk:
    - oraclejdk8

before_install:
    - yes | sdkmanager "platforms;android-27"

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: compile
      install: true
      script:
        chmod +x ./gradlew;
        ./gradlew compileDebugSources;
        ./gradlew compileReleaseSources;
    - stage: test
      install: true
      script: 
        chmod +x ./gradlew;
        ./gradlew test
    - stage: package
      install: true
      script:
        chmod +x ./gradlew;
        ./gradlew jar;
    - stage: device check
      install: true
      script:
        chmod +x ./gradlew;
        ./gradlew deviceCheck

after_script:
    # this file changes every time but should not be cached
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
