language: android
jdk: oraclejdk8
# Make it so that no state persists between builds. I.e. tests run in an environment built from scratch
# https://docs.travis-ci.com/user/reference/trusty/
sudo: required

env:
  global:
    - ANDROID_API_LEVEL=26
    - EMULATOR_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=30 # Give emulator more time to start (Default 2 minutes)

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL

    # Google APIs
    - addon-google_apis-google-$EMULATOR_API_LEVEL

    # Google Play Services
    - extra-google-google_play_services

    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image
    - sys-img-armeabi-v7a-google_apis-$EMULATOR_API_LEVEL

before_install:
    - yes | sdkmanager "platforms;android-27"

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: static analysis
      script:
        chmod +x ./gradlew;
        ./gradlew assemble;
        ./gradlew :briar-android:checkstyle;
        ./gradlew :briar-android:pmd;
        ./gradlew :briar-android:findbugs;

after_script:
    # this file changes every time but should not be cached
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
