language: android
jdk: oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=20

android:
  update_sdk: true
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26
    - android-21

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-21

before_install:
    - yes | sdkmanager "platforms;android-27"

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Emulator Management: Create, Start and Wait
before_script:
  - chmod +x ./gradlew
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator

  # Disable animations on the emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell settings put secure show_ime_with_hard_keyboard 0
  - adb shell input keyevent 82 &

script:
    - ./gradlew connectedCheck --full-stacktrace

after_script:
    # this file changes every time but should not be cached
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

after_failure: "cat /home/travis/build/CodeTaj/Briar-CodeTingz/briar-android/build/reports/androidTests/connected/index.html"